# Generated by Django 4.2.1 on 2023-05-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidade',
            name='imagem',
            field=models.ImageField(upload_to='portfolio_app/static/img/upload/habilidade/'),
        ),
    ]
