# Generated by Django 4.2.1 on 2023-05-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_habilidade_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='upload/projetos/')),
            ],
        ),
        migrations.AlterField(
            model_name='habilidade',
            name='imagem',
            field=models.ImageField(upload_to='upload/habilidade/'),
        ),
    ]
